name: Tests
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Install poetry
      #  run: pipx install poetry

      - name: Install maturin
        run: pipx install maturin

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'maturin'

      #- run: poetry install --all-extras
      - run: poetry run maturin develop --release --all-features
      - run: poetry run pytest -v

  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Install poetry
      #  run: pipx install poetry

      - name: Install maturin
        run: pipx install maturin

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'maturin'

      #- run: poetry install --all-extras
      - run: poetry run maturin develop --release --all-features
      - run: poetry run mypy ./pyobs_cloudcover